---
- name: Create network tools stack directory
  ansible.builtin.file:
    path: "{{ stacks_dir }}/network"
    state: directory
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0755'

- name: Create AdGuard Home directories
  ansible.builtin.file:
    path: "{{ appdata_dir }}/adguardhome/{{ item }}"
    state: directory
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0755'
  loop:
    - work
    - conf

- name: Configure AdGuard Home
  ansible.builtin.template:
    src: AdGuardHome.yaml.j2
    dest: "{{ appdata_dir }}/adguardhome/conf/AdGuardHome.yaml"
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0644'
  notify: restart adguardhome

- name: Deploy network tools compose file
  ansible.builtin.template:
    src: docker-compose-network.yml.j2
    dest: "{{ stacks_dir }}/network/docker-compose.yml"
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0644'

- name: Start network tools containers using compose
  community.docker.docker_compose_v2:
    project_src: "{{ stacks_dir }}/network"
    state: present
