---
# Check for existing services on Frey Pi and extract their passwords
# Run with: ansible-playbook -i inventory/hosts.yml check_existing_passwords.yml

- name: Check existing services and extract passwords
  hosts: frey
  gather_facts: no
  tasks:
    - name: Get list of all containers
      community.docker.docker_container_info:
        name: "{{ item }}"
      loop:
        - authentik_postgres
        - immich_postgres
        - mealie-db
        - adguardhome
        - qbittorrent
      register: container_info
      failed_when: false

    - name: Extract Authentik PostgreSQL password
      ansible.builtin.shell: docker exec authentik_postgres env | grep POSTGRES_PASSWORD | cut -d'=' -f2
      register: authentik_pass
      failed_when: false
      changed_when: false

    - name: Extract Immich PostgreSQL password
      ansible.builtin.shell: docker exec immich_postgres env | grep POSTGRES_PASSWORD | cut -d'=' -f2
      register: immich_pass
      failed_when: false
      changed_when: false

    - name: Extract Mealie PostgreSQL password
      ansible.builtin.shell: docker exec mealie-db env | grep POSTGRES_PASSWORD | cut -d'=' -f2
      register: mealie_pass
      failed_when: false
      changed_when: false

    - name: Check AdGuard Home container
      ansible.builtin.shell: docker ps -a --format {% raw %}'{{.Names}}'{% endraw %} | grep adguardhome
      register: adguard_check
      failed_when: false
      changed_when: false

    - name: Check qBittorrent container
      ansible.builtin.shell: docker ps -a --format {% raw %}'{{.Names}}'{% endraw %} | grep qbittorrent
      register: qbit_check
      failed_when: false
      changed_when: false

    - name: Display results
      ansible.builtin.debug:
        msg: |
          ============================================
          EXISTING SERVICES ON FREY PI
          ============================================

          Authentik PostgreSQL:
          {% if authentik_pass.rc == 0 %}
            ✓ FOUND - Password: {{ authentik_pass.stdout }}
            → Use this existing password in secrets.yml as: authentik_postgres_password
          {% else %}
            ✗ NOT FOUND - Use generated password from SECRETS_TO_ADD.yml
          {% endif %}

          Immich PostgreSQL:
          {% if immich_pass.rc == 0 %}
            ✓ FOUND - Password: {{ immich_pass.stdout }}
            → Use this existing password in secrets.yml as: immich_db_password
          {% else %}
            ✗ NOT FOUND - Use generated password from SECRETS_TO_ADD.yml
          {% endif %}

          Mealie PostgreSQL:
          {% if mealie_pass.rc == 0 %}
            ✓ FOUND - Password: {{ mealie_pass.stdout }}
            → Use this existing password in secrets.yml as: cookbook.db_password
          {% else %}
            ✗ NOT FOUND - Use generated password from SECRETS_TO_ADD.yml
          {% endif %}

          AdGuard Home:
          {% if adguard_check.rc == 0 %}
            ✓ FOUND - Set matching credentials in AdGuard web UI
          {% else %}
            ✗ NOT FOUND - Use generated credentials from SECRETS_TO_ADD.yml
          {% endif %}

          qBittorrent:
          {% if qbit_check.rc == 0 %}
            ✓ FOUND - Set matching credentials in qBittorrent web UI
          {% else %}
            ✗ NOT FOUND - Use generated credentials from SECRETS_TO_ADD.yml
          {% endif %}

          ============================================
          NEXT STEPS
          ============================================

          1. Edit your secrets file:
             ansible-vault edit group_vars/all/secrets.yml

          2. Add/update these passwords:
             - Use EXISTING passwords shown above (marked with ✓)
             - Use GENERATED passwords from SECRETS_TO_ADD.yml (marked with ✗)

          3. Deploy monitoring:
             ansible-playbook -i inventory/hosts.yml playbooks/site.yml --tags monitoring,infrastructure --ask-vault-pass

          ============================================
