---
all:
  children:
    frey_hubs:
      hosts:
        frey:
          # ansible_host: 192.168.0.252 # FreyHub (home network)
          ansible_host: 10.20.0.1 # FreyHub (WiFi AP network - ACTIVE for deployment)
          # ansible_host: frey
          # ansible_host: 10.246.88.149  # CMF
          ansible_user: ansible              # SSH user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_ansible  # SSH key
          ansible_python_interpreter: /usr/bin/python3
      vars:
        # Hub-specific variables
        is_pi5: true
        enable_hardware_acceleration: true
     
  vars:
    # Global SSH configuration
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_become: true
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3
