---
all:
  children:
    frey_hubs:
      hosts:
        frey:
          # ansible_host: 172.30.4.122  # library
          ansible_host: 10.148.210.149  # CMF
          ansible_user: ansible              # SSH user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_ansible  # SSH key
          ansible_python_interpreter: /usr/bin/python3
      vars:
        # Hub-specific variables
        is_pi5: true
        enable_hardware_acceleration: true
     
  vars:
    # Global SSH configuration
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_become: true
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3
