---
all:
  children:
    pi5_hubs:
      hosts:
        pi5-hub:
          ansible_host: 192.168.1.100  # IP of your Pi 5
          ansible_user: pi              # SSH user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa  # SSH key
          ansible_python_interpreter: /usr/bin/python3
      vars:
        # Hub-specific variables
        is_pi5: true
        enable_hardware_acceleration: true
     
  vars:
    # Global SSH configuration
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_become: true
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3
