---
all:
  children:
    pi5_hubs:
      hosts:
        pi5-hub-01:
          ansible_host: 192.168.1.100  # IP des Raspberry Pi 5 anpassen
          ansible_user: pi              # Benutzer anpassen
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          
  vars:
    # Globale SSH-Konfiguration
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_become: true
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3
