---
- name: Create power monitoring script
  ansible.builtin.template:
    src: power_monitor.py.j2
    dest: /usr/local/bin/power_monitor.py
    owner: root
    group: root
    mode: '0755'

- name: Create power monitoring systemd service
  ansible.builtin.template:
    src: power-monitor.service.j2
    dest: /etc/systemd/system/power-monitor.service
    mode: '0644'
  notify:
    - reload systemd
    - start power monitor
