---
- name: Create base directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0755'
  loop:
    - "{{ base_dir }}"
    - "{{ media_dir }}"
    - "{{ appdata_dir }}"
    - "{{ downloads_dir }}"
    - "{{ photos_dir }}"
    - "{{ ai_dir }}"
    - "{{ backups_dir }}"
    - "{{ logs_dir }}"
    - "{{ stacks_dir }}"
  tags: [directories, base]
