---
- name: Create base directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ media_user | default('media') }}"
    group: "{{ media_user | default('media') }}"
    mode: '0755'
  loop:
    - "{{ base_dir | default(storage.base_dir | default('/opt/frey')) }}"
    - "{{ media_dir | default(storage.media_dir | default((base_dir | default(storage.base_dir | default('/opt/frey'))) + '/media')) }}"
    - "{{ appdata_dir | default(storage.appdata_dir | default((base_dir | default(storage.base_dir | default('/opt/frey'))) + '/appdata')) }}"
    - "{{ downloads_dir | default((base_dir | default(storage.base_dir | default('/opt/frey'))) + '/downloads') }}"
    - "{{ photos_dir | default((media_dir | default((base_dir | default(storage.base_dir | default('/opt/frey'))) + '/media')) + '/photos') }}"
    - "{{ ai_dir | default((base_dir | default(storage.base_dir | default('/opt/frey'))) + '/ai') }}"
    - "{{ backups_dir | default((base_dir | default(storage.base_dir | default('/opt/frey'))) + '/backups') }}"
    - "{{ logs_dir | default((base_dir | default(storage.base_dir | default('/opt/frey'))) + '/logs') }}"
    - "{{ stacks_dir | default((base_dir | default(storage.base_dir | default('/opt/frey'))) + '/stacks') }}"
  tags: [directories, base]
