---
# photo_management tasks
- name: Create Immich data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0755'
  loop:
    - "{{ docker.stacks }}/immich"
    - "{{storage.appdata_dir }}/immich-db" # For PostgreSQL data

- name: Deploy Immich compose file
  ansible.builtin.template:
    src: docker-compose-immich.yml.j2
    dest: "{{ docker.stacks }}/immich/docker-compose.yml"
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0644'

- name: Start Immich stack containers using compose
  community.docker.docker_compose_v2:
    project_src: "{{ docker.stacks }}/immich"
    state: present
  register: immich_stack_result
  failed_when: immich_stack_result.failed
  changed_when: immich_stack_result.changed

