---
- name: Enable TRIM for SSD longevity
  ansible.builtin.systemd:
    name: fstrim.timer
    enabled: yes
    state: started
  when: enable_trim

- name: Enable fstrim.timer
  ansible.builtin.systemd:
    name: fstrim.timer
    state: started
    enabled: true
  when: optimization.ssd.trim

- name: Configure noatime for SSD mounts
  ansible.builtin.mount:
    path: "{{ item.mount_point }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options + ',noatime' if 'noatime' not in item.options else item.options }}"
    state: mounted
  loop: "{{ ansible_mounts | selectattr('device', 'match', '/dev/sd[a-z][1-9]') | list }}" # Adjust regex for your SSDs
  when: optimization.ssd.enable

- name: Configure swappiness for SSDs
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: true
  when: optimization.ssd.enable

- name: Reduce swappiness for SSD performance
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: yes

- name: Configure log rotation to be less frequent
  ansible.builtin.lineinfile:
    path: /etc/logrotate.conf
    regexp: '^rotate'
    line: 'rotate 4'

- name: Disable unnecessary logging to reduce SSD writes
  ansible.builtin.systemd:
    name: rsyslog
    enabled: no
    state: stopped
  when: enable_ssd_optimization
