---
- name: Update and upgrade system packages
  apt:
    upgrade: dist
    update_cache: true
    cache_valid_time: 3600
  register: apt_upgrade_result

- name: Install essential packages
  apt:
    name:
      - curl
      - wget
      - git
      - vim
      - htop
      - tree
      - unzip
      - software-properties-common
    state: present

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  notify: restart cron

- name: Configure locale
  locale_gen:
    name: "{{ locale }}"
    state: present
