---
- name: Pi5 Hub Complete Setup
  hosts: pi5_hubs
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      tags: always

  roles:
    # System Setup
    - role: common
      tags: [system, common]
    
    - role: security
      tags: [system, security]
    
    - role: ssd_optimization
      tags: [system, storage]
    
    - role: directories
      tags: [system, directories]
    
    # Docker Setup
    - role: docker
      tags: [docker, services]
    
    # Infrastructure Services
    - role: infrastructure
      tags: [docker, services, infrastructure]
    
    # Management Tools
    - role: dockge
      tags: [docker, services, management]
    
    # Monitoring Stack
    - role: monitoring
      tags: [docker, services, monitoring]
      when: enable_monitoring | default(true)
    
    # Application Stacks
    - role: media_stack
      tags: [docker, services, media]
    
    - role: ai_stack
      tags: [docker, services, ai]
    
    - role: photo_management
      tags: [docker, services, photos]
    
    - role: homeassistant
      tags: [docker, services, homeautomation]
    
    - role: networking
      tags: [docker, services, networking]
    
    - role: file_management
      tags: [docker, services, files]
    
    # System Optimization
    - role: power_management
      tags: [system, power]
    
    # Backup Strategy
    - role: backup
      tags: [system, backup]
      when: backup_enabled | default(true)

  post_tasks:
    - name: Reboot notification
      debug:
        msg: "Setup completed! Consider rebooting the system for all changes to take effect."
      tags: always
