---
- name: Create AI stack directory
  ansible.builtin.file:
    path: "{{ stacks_dir }}/ai"
    state: directory
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0755'

- name: Deploy AI stack compose file
  ansible.builtin.template:
    src: docker-compose-ai.yml.j2
    dest: "{{ stacks_dir }}/ai/docker-compose.yml"
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0644'

- name: Start AI stack containers using compose
  community.docker.docker_compose_v2:
    project_src: "{{ stacks_dir }}/ai"
    state: present
  when: not ansible_check_mode
