---
- name: Setup media stack user
  include_tasks: "templates/create_user.yml"
  vars:
    stack: "docker" 
    folders: [stacks]


- name: Deploy Dockge compose file
  ansible.builtin.template:
    src: docker-compose-dockge.yml.j2
    dest: "{{ docker.stacks }}/docker/docker-compose.yml"
    owner: "{{ docker.user.name }}"
    group: "{{ docker.group.name }}"
    mode: '0644'

- name: Start Dockge container using compose
  community.docker.docker_compose_v2:
    project_src: "{{ docker.stacks }}/docker"
    state: present
  when: not ansible_check_mode
