---
- name: Create Dockge directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0755'
  loop:
    - "{{ stacks_dir }}/dockge"

- name: Deploy Dockge compose file
  ansible.builtin.template:
    src: docker-compose-dockge.yml.j2
    dest: "{{ stacks_dir }}/dockge/docker-compose.yml"
    owner: "{{ media_user }}"
    group: "{{ media_user }}"
    mode: '0644'

- name: Start Dockge container using compose
  community.docker.docker_compose_v2:
    project_src: "{{ stacks_dir }}/dockge"
    state: present
  when: not ansible_check_mode
